name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  static-analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: |
          sudo apt update
          sudo apt install cppcheck

      - name: Clone
        uses: actions/checkout@v4

      - name: cppcheck
        run: cppcheck --std=c++17 src/

  code-format:
    name: Code format check

    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: clang-format
        run: find src -type f -name \*.cc -o -name \*.h | xargs clang-format --dry-run --Werror

  android:
    name: Android

    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: os/android/app/.cxx
          key: android-cmake-v101

      - name: Setup signing config
        if: env.KEYSTORE_FILE_BASE64 != '' && env.KEYSTORE_PROPERTIES_FILE_BASE64 != ''
        run: |
          cd os/android
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > debug.keystore
          echo "$KEYSTORE_PROPERTIES_FILE_BASE64" | base64 --decode > debug-keystore.properties
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.ANDROID_DEBUG_KEYSTORE_FILE_BASE64 }}
          KEYSTORE_PROPERTIES_FILE_BASE64: ${{ secrets.ANDROID_DEBUG_KEYSTORE_PROPERTIES_FILE_BASE64 }}

      - name: Build
        run: |
          cd os/android
          ./gradlew assembleDebug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce-debug.apk
          path: os/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

  ios:
    name: iOS

    runs-on: macos-14

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: out
          key: ios-cmake-v5

      - name: Configure
        run: |
          cmake --preset ios

      - name: Build
        run: |
          cmake --build --preset ios-debug

      - name: Pack
        run: |
          cd out/build/ios
          cpack -C Debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce.ipa
          path:  out/build/ios/fallout-ce.ipa
          retention-days: 7

  linux:
    name: Linux (${{ matrix.arch }})

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - x64

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies (x86)
        if: matrix.arch == 'x86'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install g++-multilib libsdl2-dev:i386 zlib1g-dev:i386

      - name: Dependencies (x64)
        if: matrix.arch == 'x64'
        run: |
          sudo apt update
          sudo apt install libsdl2-dev zlib1g-dev

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: out
          key: linux-${{ matrix.arch }}-cmake-v101

      - name: Configure
        run: |
          cmake --preset linux-${{ matrix.arch }}-debug

      - name: Build
        run: |
          cmake --build --preset linux-${{ matrix.arch }}-debug

      - name: Package
        run: |
          tar -czvf out/build/linux-${{ matrix.arch }}-debug/fallout-ce-linux-${{ matrix.arch }}.tar.gz -C out/build/linux-${{ matrix.arch }}-debug fallout-ce

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce-linux-${{ matrix.arch }}
          path: out/build/linux-${{ matrix.arch }}-debug/fallout-ce-linux-${{ matrix.arch }}.tar.gz
          retention-days: 7

  linux-arm:
    name: Linux (${{ matrix.arch }})

    runs-on: ubuntu-22.04-arm

    strategy:
      fail-fast: false
      matrix:
        arch:
          - armhf
          - arm64

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies (armhf)
        if: matrix.arch == 'armhf'
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt update
          sudo apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libsdl2-dev:armhf zlib1g-dev:armhf

      - name: Dependencies (arm64)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt update
          sudo apt install libsdl2-dev zlib1g-dev

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: linux-${{ matrix.arch }}-cmake-v101

      - name: Configure (armhf)
        if: matrix.arch == 'armhf'
        run: |
          cmake \
            -B build \
            -D CMAKE_BUILD_TYPE=Debug \
            -D FALLOUT_VENDORED=OFF \
            -D CMAKE_SYSTEM_PROCESSOR=arm \
            -D CMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -D CMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
            # EOL

      - name: Configure (arm64)
        if: matrix.arch == 'arm64'
        run: |
          cmake \
            -B build \
            -D CMAKE_BUILD_TYPE=Debug \
            -D FALLOUT_VENDORED=OFF \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            -j $(nproc) \
            # EOL

      - name: Package
        run: |
          tar -czvf build/fallout-ce-linux-${{ matrix.arch }}.tar.gz -C build fallout-ce

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce-linux-${{ matrix.arch }}
          path: build/fallout-ce-linux-${{ matrix.arch }}.tar.gz
          retention-days: 7

  macos:
    name: macOS

    runs-on: macos-14

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: out
          key: macos-cmake-v6

      - name: Configure
        run: |
          cmake --preset macos

      - name: Build
        run: |
          cmake --build --preset macos-debug

      - name: Pack
        run: |
          cd out/build/macos
          cpack -C Debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce-macos.dmg
          path:  out/build/macos/Fallout Community Edition.dmg
          retention-days: 7

  windows:
    name: Windows (${{ matrix.arch }})

    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
            generator-platform: Win32
          - arch: x64
            generator-platform: x64

    steps:
      - name: Clone
        uses: actions/checkout@v4
     
      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: out
          key: windows-${{ matrix.arch }}-cmake-v103

      - name: Configure
        run: |
          cmake --preset windows-${{ matrix.arch }}
            
      - name: Build
        run: |
          cmake --build --preset windows-${{ matrix.arch }}-debug

      - name: Package
        run: |
          cd out/build/windows-${{ matrix.arch }}/Debug
          7z a fallout-ce-windows-${{ matrix.arch }}.zip fallout-ce.exe
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce-windows-${{ matrix.arch }}
          path: out/build/windows-${{ matrix.arch }}/Debug/fallout-ce-windows-${{ matrix.arch }}.zip
          retention-days: 7


  release:
    name: Experimental build
    runs-on: ubuntu-latest
    needs: [android, ios, linux, linux-arm, macos, windows]
    permissions: write-all
    steps:
      - name: Search artifacts
        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: actions/download-artifact@v4.3.0
        with:
          path: artifacts/

      - name: Remove old version
        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move unpacked artifacts to main folder
        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          ls -Rlah .
          find .
          cd artifacts/
          for folder in *; do
            if [[ -d "$folder" && "$folder" != "." ]]; then
              echo "Processing $folder"
              mv "$folder" "$folder.dir"
              cd "$folder.dir"
              for file in *; do
                if [ -f "$file" ]; then
                  if [ -f "../$file" ]; then
                    echo "ERROR: Duplicate artifact file name $file"
                    exit 1
                  fi
                  if [ -d "../$file" ]; then
                    echo "ERROR: Duplicate artifact folder $file"
                    exit 1
                  fi

                  echo "Moving $file"
                  mv "$file" "../$file"
                fi
              done
              cd ..
              rm -rf "$folder.dir"
            fi
          done
          ls -Rlah .
          find .
          cd ../

      - name: Allow GitHub to remove release for an few seconds
        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          sleep 20s

      - name: Upload new release
        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/*
          tag_name: main
          draft: false
          prerelease: true
          name: OpenVault Experimental Build
